# Generated by Django 3.0.6 on 2020-05-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('index', '0001_initial'),
	]

	operations = [
		migrations.RenameField(
			model_name='memes',
			old_name='meme_timestamp',
			new_name='meme_datetime',
		),
	]
